spring:
  application.name: demo-cache-application
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: admin
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate.dialact: org.hibernate.dialect.PostgreSQL9Dialect